version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm run start-watch
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV-development}

  redirect:
    extends:
      service: base-app
    ports:
      - 3000:3000
    volumes:
      - redirect-node_modules:/code/node_modules

volumes:
  redirect-node_modules:
